kubectl delete pod backend-feed-*
kubectl delete pod backend-feed-*
kubectl delete pod backend-user-*
kubectl delete pod backend-user-*
kubectl delete pod reverseproxy-*
kubectl delete pod reverseproxy-*
kubectl delete pod udagram-frontend-*
kubectl delete pod udagram-frontend-*
kubectl apply -f aws-secret.yaml
kubectl apply -f env-configmap.yaml
kubectl apply -f env-secret.yaml
kubectl apply -f reverseproxy-deployment.yml
kubectl apply -f reverseproxy-service.yml
kubectl apply -f frontend-deployment.yml
kubectl apply -f frontend-service.yml
kubectl apply -f user-deployment.yml
kubectl apply -f user-service.yml
kubectl apply -f feed-deployment.yml
kubectl apply -f feed-service.yml
