name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy the Docker image
      run: |
        # docker build -t udagram-api-feed ./udagram-api-feed
        # docker tag udagram-api-feed jeraldlashy/udagram-api-feed

        # docker build -t udagram-api-user ./udagram-api-user
        # docker tag udagram-api-user jeraldlashy/udagram-api-user

        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend jeraldlashy/udagram-frontend

        # docker build -t reverseproxy ./udagram-reverseproxy
        # docker tag reverseproxy jeraldlashy/reverseproxy

        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        # docker push jeraldlashy/udagram-api-feed
        # docker push jeraldlashy/udagram-api-user
        docker push jeraldlashy/udagram-frontend
        # docker push jeraldlashy/reverseproxy
